services:
  meu-blog:
    build: .
    container_name: meu-blog
    restart: unless-stopped
    networks:
      - outside
    volumes:
      - data:/data
      - uploads:/var/www/html/uploads
volumes:
  data:
  uploads:
networks:
  outside:
    external: true
